name: Deploy README as webpage

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdown to HTML
        uses: wranders/markdown-to-pages-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: README.md
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
