name: Deploy README to Pages

on:
  push:
    branches: ["main"]
    paths:
      - 'README.md'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
